name: Ping Websites Every 10 Minutes for 6 Hours

on:
  workflow_dispatch:  # manual trigger
  # Optional: trigger once a day to kickstart it
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run 6-hour ping loop
        run: |
          echo "Starting 6-hour ping loop..."
          python pinger.py
